### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by GeARCraft1** [warmsea/node-rfr#2]
Hi! I'm trying to use rfr on Windows and i'm recieving the following error:
module.js:338
    throw err;
          ^
Error: Cannot find module 'lib/logger'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.<anonymous> (C:\Users\Administrator.NATAL\Desktop\ServerAdmin\P
fferPanel\node_modules\rfr\lib\rfr.js:159:12)
    at Object.<anonymous> (C:\Users\Administrator.NATAL\Desktop\ServerAdmin\Puf
erPanel\index.js:12:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
The module isn't installed as global, and the problem isn the administrator account or machine. I can sucessfullt use the require('./lib/logger') if the file is in the root of the Project.
Can anyone help me please??

**Comment by jonnolen** [comment]
I'm also getting an error on windows.

rfr is a module in my package, i'm loading it in using require('rfr').  when I do that I get a message saying: `Using rfr as a global module is error-prone.`

npm list -g lists no global modules installed so it is not a global module.

**Comment by warmsea** [comment]
Sorry, I never tested it on Windows. I'll find a Windows machine to figure out what's wrong.

**Comment by warmsea** [comment]
Please try v1.2.3.
